version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: theatre_db
      POSTGRES_USER: theatre_user
      POSTGRES_PASSWORD: theatre_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://theatre_user:theatre_password@db:5432/theatre_db

volumes:
  postgres_data:
